[package]
name = "litehouse-plugin-macro"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A macro for generating Litehouse plugins"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.76"
quote = "1.0.35"
syn = { version = "2.0.46", features = ["full"] }
