cargo-features = ["codegen-backend"]


[workspace]
members = ["crates/*"]
resolver = "2"

[profile.release]
strip = true
opt-level = "z"
lto = true

[profile.release-with-debug]
inherits = "release"
debug = true
strip = false
lto = false


# [profile.dev]
# codegen-backend = "cranelift"

[patch.crates-io]
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime.git", rev = "4d54a99" }
wasmtime-wasi = { git = "https://github.com/bytecodealliance/wasmtime.git", rev = "4d54a99" }
wasmtime-wasi-http = { git = "https://github.com/bytecodealliance/wasmtime.git", rev = "4d54a99" }

[workspace.metadata.groups]
plugins = [
    "path:crates/samsung",
    "path:crates/sonoff",
    "path:crates/tasmota",
    "path:crates/weather",
]