[workspace]
members = ["crates/*"]
resolver = "2"

[profile.release]
strip = true
opt-level = "z"
lto = true

[patch.crates-io]
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime.git", rev = "b546a5f" }
wasmtime-wasi = { git = "https://github.com/bytecodealliance/wasmtime.git", rev = "b546a5f" }
wasmtime-wasi-http = { git = "https://github.com/bytecodealliance/wasmtime.git", rev = "b546a5f" }
wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen.git" }
