/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Entry {
  title: string;
  version: Array<number>;
  description: string;
  capabilities: Array<string>;
  schema: string;
  size: number;
  sha: string;
}
export type JsLitehouseRegistry = LitehouseRegistry;
export class LitehouseRegistry {
  static global(): Promise<JsLitehouseRegistry>;
  get(title: string): Array<Entry>;
  insert(entry: Entry): undefined | null;
  getExact(title: string, version: [number, number, number]): Entry | null;
}
