/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Entry {
  title: string
  version: Array<number>
  description: string
  capabilities: Array<string>
  schema: string
  size: number
  sha: string
}
export type JsLitehouseRegistry = LitehouseRegistry
export class LitehouseRegistry {
  constructor()
  insert(entry: Entry): Promise<undefined | null>
  get(title: string): Promise<Array<Entry>>
  getPrefix(prefix: string): Promise<Array<Entry>>
}
