[build]
rustflags = ["--cfg", "tokio_unstable", "-Zthreads=16"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["--cfg", "tokio_unstable", "-Zthreads=16"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
