package litehouse:plugin;

interface plugin {
    use update.{update};

    record event {
        id: u64,
        timestamp: u64,
        inner: update,
    }

    variant subscription {
      time(time-subscription),
      update(update-subscription),
    }

    variant update-subscription {
      temperature,
      wind-speed,
      current,
      voltage,
      power,
      on-off
    }

    variant time-subscription {
      every(every),
      at(u64),
    }

    record every {
      amount: u64,
      unit: time-unit,
    }

    variant time-unit {
      second,
      minute,
      hour,
      day,
      week,
      month,
      year,
    }

    variant output {
      notify,
    }

    resource runner {
      constructor(nickname: string, config: option<string>);
      subscribe: func() -> result<list<subscription>, u32>;
      update: func(events: list<event>) -> result<bool, u32>;
      outputs: func() -> result<list<output>, u32>;
    }

    record metadata {
      version: string,
      identifier: string,
      config-schema: option<string>,
      author: option<string>,
      homepage: option<string>,
      source: option<string>,
      description: option<string>,
      readme: option<string>,
      capabilities: list<string>,
    }

    get-metadata: func() -> metadata;
}

interface notify {
    // An additional interface for plugins that can notify the user
    resource notify {
        constructor();
        notify: func(message: string) -> result<bool, u32>;
    }
}

// note: we import this so we can't export it (ie. keep it in plugin)
//       https://github.com/WebAssembly/component-model/issues/272
interface update {
    variant update {
        time(u64),

        temperature(f64),
        wind-speed(f64),

        current(f64),
        voltage(u16),
        power(u16),
        on-off(bool),
    }
}

world plugin-host {
  import wasi:http/outgoing-handler@0.2.8;
  import wasi:sockets/tcp@0.2.8;
  import wasi:sockets/tcp-create-socket@0.2.8;
  import wasi:sockets/instance-network@0.2.8;

  import host: interface {
    use update.{update};
    send-update: func(nickname: string, update: update);
  }

  export plugin;
}
