"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bEfijwCHtYK
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import { CopyButton } from "./code-block";

function classNames(...classes: (string | undefined)[]) {
  return classes.filter(Boolean).join(" ");
}

export function CopyBox({
  command,
  className,
  beforeCopy,
}: {
  command: string;
  className?: string;
  beforeCopy?: () => boolean;
}) {
  return (
    <div
      className={classNames(
        "group flex items-center border-accent bg-secondary border font-mono",
        className,
      )}
    >
      <div className="flex-1 p-3 text-sm overflow-x-scroll text-nowrap">
        {command}
      </div>
      <CopyButton
        onCopy={() => {
          const accept = beforeCopy?.();
          if (accept === false) return false;
          navigator.clipboard.writeText(command);
          return true;
        }}
      />
    </div>
  );
}
