"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bEfijwCHtYK
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import { CopyButton } from "./code-block";

function classNames(...classes: (string | undefined)[]) {
  return classes.filter(Boolean).join(" ");
}

export function CopyBox({
  command,
  className,
}: {
  command: string;
  className?: string;
}) {
  return (
    <div
      className={classNames(
        "pl-4 group flex items-center border-accent bg-secondary border gap-4 font-mono",
        className,
      )}
    >
      <span className="flex-1 text-sm">{command}</span>
      <CopyButton
        onCopy={() => {
          console.log(command);
        }}
      />
    </div>
  );
}
