"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/zjy70IVXKPe
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { useManifestStore } from "@/hooks/use-indexed-db";
import type { SVGProps } from "react";
import { ManifestButton } from "./manifest-button";

export function ManifestEditor() {
  const { items } = useManifestStore();

  return (
    <Sheet>
      <SheetTrigger asChild>
        <ManifestButton items={items} />
      </SheetTrigger>
      <SheetContent side="right">
        <div className="flex flex-col h-full">
          <div>
            <h3 className="text-lg font-semibold">Manifest</h3>
            <pre className="mt-2 overflow-auto bg-gray-100 p-3 rounded-md font-mono text-sm dark:bg-muted/20">
              {JSON.stringify(
                {
                  $schema: "./schema.json",
                  plugins: {},
                  imports: items?.map((item) => item.id),
                },
                null,
                2,
              )}
            </pre>
          </div>
          <div className="flex-1 overflow-auto">
            <h3 className="text-lg font-semibold">Plugins</h3>
            <div className="mt-2 grid grid-cols-[1fr_auto_auto] items-center gap-4">
              <div className="flex items-center gap-4">
                <h4 className="font-medium">Tailwind CSS</h4>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  v3.2.7
                </p>
              </div>
              <div className="text-sm text-gray-500 dark:text-gray-400">
                <DownloadIcon className="w-4 h-4" />
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">1.2M</p>
            </div>
            <div className="mt-2 grid grid-cols-[1fr_auto_auto] items-center gap-4">
              <div className="flex items-center gap-4">
                <h4 className="font-medium">React</h4>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  v18.2.0
                </p>
              </div>
              <div className="text-sm text-gray-500 dark:text-gray-400">
                <DownloadIcon className="w-4 h-4" />
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">2.1M</p>
            </div>
            <div className="mt-2 grid grid-cols-[1fr_auto_auto] items-center gap-4">
              <div className="flex items-center gap-4">
                <h4 className="font-medium">Next.js</h4>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  v13.2.3
                </p>
              </div>
              <div className="text-sm text-gray-500 dark:text-gray-400">
                <DownloadIcon className="w-4 h-4" />
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">1.8M</p>
            </div>
          </div>
        </div>
      </SheetContent>
    </Sheet>
  );
}

function DownloadIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <title>Download</title>
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>
  );
}
