/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/IeZF9j1Xy5j
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import type { SVGProps } from "react";

export function RegistryItem() {
  return (
    <div key="1" className="grid grid-cols-2 gap-8 p-8 md:p-12 lg:p-16">
      <div className="space-y-6">
        <div className="space-y-2">
          <h2 className="text-2xl font-bold">
            Acme
            <span className="font-mono">Plugin</span>
          </h2>
          <div className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
            <DownloadIcon className="h-4 w-4" />
            <span>
              <span className="font-mono">12,345</span>
              downloads{"\n"}
            </span>
          </div>
        </div>
        <div className="space-y-2">
          <h3 className="text-lg font-medium">
            Version
            <span className="font-mono">History</span>
          </h3>
          <div className="space-y-1 text-sm">
            <div className="flex items-center justify-between bg-green-100 border border-gray-200 rounded-md dark:border-gray-800">
              <span className="font-mono">v2.1.0</span>
              <span className="text-gray-500 dark:text-gray-400">
                May 13, 2024
              </span>
            </div>
            <div className="flex items-center justify-between">
              <span className="font-mono">v2.0.0</span>
              <span className="text-gray-500 dark:text-gray-400">
                Apr 22, 2024
              </span>
            </div>
            <div className="flex items-center justify-between">
              <span className="font-mono">v1.5.2</span>
              <span className="text-gray-500 dark:text-gray-400">
                Mar 18, 2024
              </span>
            </div>
          </div>
        </div>
        <div className="space-y-2">
          <h3 className="text-lg font-medium">
            <span className="font-mono">Details</span>
          </h3>
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div className="flex items-center gap-2">
              <FileIcon className="h-4 w-4" />
              <span>
                <span className="font-mono">2.3 MB</span>
              </span>
            </div>
            <div className="flex items-center gap-2">
              <PackageIcon className="h-4 w-4" />
              <span className="font-mono">v2.1.0</span>
            </div>
          </div>
        </div>
        <div className="space-y-2">
          <h3 className="text-lg font-medium">
            <span className="font-mono">Description</span>
          </h3>
          <p className="text-sm text-gray-500 dark:text-gray-400">
            The Acme Plugin is a powerful tool that enhances your workflow and
            streamlines your development process. With its intuitive interface
            and robust features, you can easily customize and extend your
            applications.
          </p>
        </div>
      </div>
      <div className="space-y-6">
        <div className="space-y-2">
          <h3 className="text-lg font-medium">
            <span className="font-mono">Configuration</span>
          </h3>
          <div className="rounded-md border border-gray-200 bg-gray-100 p-4 dark:border-gray-800 dark:bg-gray-950">
            <pre className="font-mono text-sm">
              {`{
            "apiKey": "abc123",
            "endpoint": "https://api.example.com",
            "debug": true
          }`}
            </pre>
          </div>
        </div>
        <div className="rounded-md border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-gray-950">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Key</TableHead>
                <TableHead>Value</TableHead>
                <TableHead>Type</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell className="font-mono">apiKey</TableCell>
                <TableCell>abc123</TableCell>
                <TableCell className="font-mono">string</TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-mono">endpoint</TableCell>
                <TableCell>https://api.example.com</TableCell>
                <TableCell className="font-mono">string</TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-mono">debug</TableCell>
                <TableCell>true</TableCell>
                <TableCell className="font-mono">boolean</TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </div>
    </div>
  );
}

function DownloadIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <title>Download</title>
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>
  );
}

function FileIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <title>File</title>
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
    </svg>
  );
}

function PackageIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <title>Package Icon</title>
      <path d="m7.5 4.27 9 5.15" />
      <path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z" />
      <path d="m3.3 7 8.7 5 8.7-5" />
      <path d="M12 22V12" />
    </svg>
  );
}
